language: generic
script: make build/SymatemAPI
matrix:
  include:
    # - os: linux
    #   compiler: gcc-6
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test']
    #       packages: ['gcc-6']
    #   env: CC=gcc-6 CXX=g++-6
    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['llvm-3.9', 'clang-3.9']
      env: CC=clang-3.9 CXX=clang++-3.9
    - os: osx
      osx_image: xcode7.3
      compiler: clang
addons:
  ssh_known_hosts: mfelten.de
before_install:
  - openssl aes-256-cbc -K $encrypted_778e046e3e91_key -iv $encrypted_778e046e3e91_iv -in travis/travis_id_rsa.enc -out travis/travis_id_rsa -d
  - chmod 400 travis/travis_id_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: (cd ./build;tar cvf Symatem_$(uname -s)_$(uname -p).tar *)
    script: scp -i travis/travis_id_rsa ./build/Symatem_${uname).tar mfelten_de@mfelten.de:/home/mfelten_de/docroot/Symatem/
