language: generic
script: make build/SymatemAPI
matrix:
  include:
    # - os: linux
    #   compiler: gcc-6
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test']
    #       packages: ['gcc-6']
    #   env: CC=gcc-6 CXX=g++-6
    - os: linux
      compiler: clang-4.0
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['llvm-4.0', 'clang-4.0']
      env: CC=clang-4.0 CXX=clang++-4.0
    - os: osx
      osx_image: xcode7.3
      compiler: clang
