language: cpp
script: make test
matrix:
  include:
    - os: linux
      compiler: gcc6
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: CC=gcc-6 CXX=g++-6
    - os: linux
      compiler: clang39
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.9']
      env: CC=clang-3.9 CXX=clang++-3.9
    - os: osx
      osx_image: xcode7.3
      compiler: clang
