language: cpp
matrix:
  include:
    - os: linux
      env: COMPILER=clang-3.9
    - os: linux
      env: COMPILER=gcc-6
    - os: osx
      osx_image: xcode7.3
      env: COMPILER=clang
script: make test
